#pragma once

enum ServerDisconnectIdentifiers {
	UNKNOWN_SERVER_ERROR = 0,
	DUPLICATE_LOGIN = 4,
	SERVER_SHUTDOWN = 5,
	SERVER_MAP_LOAD_FAILURE = 6,
	INVALID_SESSION_KEY = 7,
	ACCOUNT_NOT_IN_PENDING_LIST = 8,
	CHARACTER_NOT_FOUND = 9,
	CHARACTER_CORRUPTED = 10,
	KICK = 11,
	FREE_TRIAL_EXPIRED = 12,
	PLAY_SCHEDULE_TIME_DONE = 13
};

enum CONNECTION_TYPE {
	CONN_SERVER = 0,
	CONN_AUTH,
	CONN_CHAT,
	CONN_UNKNOWN,
	CONN_WORLD,
	CONN_CLIENT
};

enum SERVER {
	MSG_SERVER_VERSION_CONFIRM = 0,
	MSG_SERVER_DISCONNECT_NOTIFY,
	MSG_SERVER_GENERAL_NOTIFY
};

enum AUTH {
	MSG_AUTH_LOGIN_REQUEST = 0,
	MSG_AUTH_LOGOUT_REQUEST,
	MSG_AUTH_CREATE_NEW_ACCOUNT_REQUEST,
	MSG_AUTH_LEGOINTERFACE_AUTH_RESPONSE,
	MSG_AUTH_SESSIONKEY_RECEIVED_CONFIRM,
	MSG_AUTH_RUNTIME_CONFIG
};

enum WORLD {
	MSG_WORLD_CLIENT_VALIDATION = 1, //Includes session info
	MSG_WORLD_CLIENT_CHARACTER_LIST_REQUEST,
	MSG_WORLD_CLIENT_CHARACTER_CREATE_REQUEST,
	MSG_WORLD_CLIENT_LOGIN_REQUEST, //Hit play on char select
	MSG_WORLD_CLIENT_GAME_MSG,
	MSG_WORLD_CLIENT_CHARACTER_DELETE_REQUEST,
	MSG_WORLD_CLIENT_CHARACTER_RENAME_REQUEST,
	MSG_WORLD_CLIENT_HAPPY_FLOWER_MODE_NOTIFY,
	MSG_WORLD_CLIENT_SLASH_RELOAD_MAP,  
	MSG_WORLD_CLIENT_SLASH_PUSH_MAP_REQUEST,  
	MSG_WORLD_CLIENT_SLASH_PUSH_MAP, 
	MSG_WORLD_CLIENT_SLASH_PULL_MAP,
	MSG_WORLD_CLIENT_LOCK_MAP_REQUEST,
	MSG_WORLD_CLIENT_GENERAL_CHAT_MESSAGE,
	MSG_WORLD_CLIENT_HTTP_MONITOR_INFO_REQUEST,
	MSG_WORLD_CLIENT_SLASH_DEBUG_SCRIPTS, 
	MSG_WORLD_CLIENT_MODELS_CLEAR,
	MSG_WORLD_CLIENT_EXHIBIT_INSERT_MODEL,
	MSG_WORLD_CLIENT_LEVEL_LOAD_COMPLETE,
	MSG_WORLD_CLIENT_TMP_GUILD_CREATE,
	MSG_WORLD_CLIENT_ROUTE_PACKET, //Route to chat server
	MSG_WORLD_CLIENT_POSITION_UPDATE,
	MSG_WORLD_CLIENT_MAIL,
	MSG_WORLD_CLIENT_WORD_CHECK, 
	MSG_WORLD_CLIENT_STRING_CHECK,  
	MSG_WORLD_CLIENT_GET_PLAYERS_IN_ZONE,
	MSG_WORLD_CLIENT_REQUEST_UGC_MANIFEST_INFO,
	MSG_WORLD_CLIENT_BLUEPRINT_GET_ALL_DATA_REQUEST,
	MSG_WORLD_CLIENT_CANCEL_MAP_QUEUE,
	MSG_WORLD_CLIENT_HANDLE_FUNNESS,
	MSG_WORLD_CLIENT_FAKE_PRG_CSR_MESSAGE,
	MSG_WORLD_CLIENT_REQUEST_FREE_TRIAL_REFRESH,
	MSG_WORLD_CLIENT_GM_SET_FREE_TRIAL_STATUS
};

enum CLIENT {
	MSG_CLIENT_LOGIN_RESPONSE = 0,
	MSG_CLIENT_LOGOUT_RESPONSE,
	MSG_CLIENT_LOAD_STATIC_ZONE,
	MSG_CLIENT_CREATE_OBJECT,
	MSG_CLIENT_CREATE_CHARACTER,
	MSG_CLIENT_CREATE_CHARACTER_EXTENDED,
	MSG_CLIENT_CHARACTER_LIST_RESPONSE,
	MSG_CLIENT_CHARACTER_CREATE_RESPONSE,
	MSG_CLIENT_CHARACTER_RENAME_RESPONSE,
	MSG_CLIENT_CHAT_CONNECT_RESPONSE,
	MSG_CLIENT_AUTH_ACCOUNT_CREATE_RESPONSE,
	MSG_CLIENT_DELETE_CHARACTER_RESPONSE,
	MSG_CLIENT_GAME_MSG,
	MSG_CLIENT_CONNECT_CHAT,
	MSG_CLIENT_TRANSFER_TO_WORLD,
	MSG_CLIENT_IMPENDING_RELOAD_NOTIFY,
	MSG_CLIENT_MAKE_GM_RESPONSE,
	MSG_CLIENT_HTTP_MONITOR_INFO_RESPONSE,
	MSG_CLIENT_SLASH_PUSH_MAP_RESPONSE,
	MSG_CLIENT_SLASH_PULL_MAP_RESPONSE,
	MSG_CLIENT_SLASH_LOCK_MAP_RESPONSE,
	MSG_CLIENT_BLUEPRINT_SAVE_RESPONSE,
	MSG_CLIENT_BLUEPRINT_LUP_SAVE_RESPONSE,
	MSG_CLIENT_BLUEPRINT_LOAD_RESPONSE_ITEMID,
	MSG_CLIENT_BLUEPRINT_GET_ALL_DATA_RESPONSE,
	MSG_CLIENT_MODEL_INSTANTIATE_RESPONSE,
	MSG_CLIENT_DEBUG_OUTPUT,
	MSG_CLIENT_ADD_FRIEND_REQUEST,
	MSG_CLIENT_ADD_FRIEND_RESPONSE,
	MSG_CLIENT_REMOVE_FRIEND_RESPONSE,
	MSG_CLIENT_GET_FRIENDS_LIST_RESPONSE,
	MSG_CLIENT_UPDATE_FRIEND_NOTIFY,
	MSG_CLIENT_ADD_IGNORE_RESPONSE,
	MSG_CLIENT_REMOVE_IGNORE_RESPONSE,
	MSG_CLIENT_GET_IGNORE_LIST_RESPONSE,
	MSG_CLIENT_TEAM_INVITE,
	MSG_CLIENT_TEAM_INVITE_INITIAL_RESPONSE,
	MSG_CLIENT_GUILD_CREATE_RESPONSE,
	MSG_CLIENT_GUILD_GET_STATUS_RESPONSE,
	MSG_CLIENT_GUILD_INVITE,
	MSG_CLIENT_GUILD_INVITE_INITIAL_RESPONSE,
	MSG_CLIENT_GUILD_INVITE_FINAL_RESPONSE,
	MSG_CLIENT_GUILD_INVITE_CONFIRM,
	MSG_CLIENT_GUILD_ADD_PLAYER,
	MSG_CLIENT_GUILD_REMOVE_PLAYER,
	MSG_CLIENT_GUILD_LOGIN_LOGOUT,
	MSG_CLIENT_GUILD_RANK_CHANGE,
	MSG_CLIENT_GUILD_DATA,
	MSG_CLIENT_GUILD_STATUS,
	MSG_CLIENT_MAIL,
	MSG_CLIENT_DB_PROXY_RESULT,
	MSG_CLIENT_SHOW_ALL_RESPONSE,
	MSG_CLIENT_WHO_RESPONSE,
	MSG_CLIENT_SEND_CANNED_TEXT,
	MSG_CLIENT_UPDATE_CHARACTER_NAME,
	MSG_CLIENT_SET_NETWORK_SIMULATOR,
	MSG_CLIENT_INVALID_CHAT_MESSAGE,
	MSG_CLIENT_MINIMUM_CHAT_MODE_RESPONSE,
	MSG_CLIENT_MINIMUM_CHAT_MODE_RESPONSE_PRIVATE,
	MSG_CLIENT_CHAT_MODERATION_STRING,
	MSG_CLIENT_UGC_MANIFEST_RESPONSE,
	MSG_CLIENT_IN_LOGIN_QUEUE,
	MSG_CLIENT_SERVER_STATES,
	MSG_CLIENT_GM_CLOSE_TARGET_CHAT_WINDOW,
	MSG_CLIENT_GENERAL_TEXT_FOR_LOCALIZATION,
	MSG_CLIENT_UPDATE_FREE_TRIAL_STATUS
};